spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.212/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell2

wechat:
  mpAppId: wx8b298abbb1687404
  mpAppSecret: 157436a4cec18c106c5356bb59a11d59
