spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.164/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.164
    port: 6379
server:
  context-path: /sell2

wechat:
  mpAppId: wx8b298abbb1687404
  mpAppSecret: 157436a4cec18c106c5356bb59a11d59
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath:
  notifyUrl: http://baishuhao.natapp1.cc/sell2/pay/notify

projectUrl:
  wechatMpAuthorize: http://baishuihao.natapp4.cn
  wechatOpenAuthorize: http://baishuihao.natapp4.cn
  sell: http://baishuihao.natapp4.cn
